### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tankche1** [wpeebles/gangealing#11]
Hi, I try to run any command and will get this error:

~~~

No CUDA runtime is found, using CUDA_HOME='/cm/shared/apps/cuda100/10.0.130'
Traceback (most recent call last):
  File "applications/propagate_to_images.py", line 20, in <module>
    from applications import base_eval_argparse, load_stn, determine_flips
  File "/home/user/nvidia_code/gangealing/applications/__init__.py", line 3, in <module>
    from models import get_stn, ResnetClassifier
  File "/home/user/nvidia_code/gangealing/models/__init__.py", line 3, in <module>
    from models.spatial_transformers.spatial_transformer import get_stn, ComposedSTN, SpatialTransformer
  File "/home/user/nvidia_code/gangealing/models/spatial_transformers/spatial_transformer.py", line 5, in <module>
    from models.stylegan2.networks import EqualLinear, ConvLayer, ResBlock
  File "/home/user/nvidia_code/gangealing/models/stylegan2/networks.py", line 6, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "/home/user/nvidia_code/gangealing/models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/user/nvidia_code/gangealing/models/stylegan2/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/user/anaconda2/envs/gg/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/user/anaconda2/envs/gg/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/user/anaconda2/envs/gg/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1456, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/home/user/anaconda2/envs/gg/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1857, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/home/user/anaconda2/envs/gg/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
~~~

THe command I run is :  python applications/propagate_to_images.py --ckpt cat --real_data_path data/lsun_cats --real_size 512 --dset_indices 1922 2363 8558 7401 9750 7432 2105 53 1946

Any help would be appreciated.

**Comment by wpeebles** [comment]
Hi @tankche1. It looks like your environment is either having trouble finding CUDA or building the CUDA extensions from the [rosinality StyleGAN2 repo](https://github.com/rosinality/stylegan2-pytorch).

Can you verify CUDA/cuDNN is working:

```
import torch
x = torch.randn(2, 3, device='cuda')
print(x)
print('success')
```

And if that works, try this (running from the `gangealing` directory):

```
from gangealing.models.stylegan2.networks import Generator
g = Generator(128, 512, 8).to('cuda')
print('success')
```

**Comment by tankche1** [comment]
THanks!
Uninstall pytorch and install pytorch with the right CUDA version solve the problem

**Comment by tankche1** [comment]
THanks again for the great work. 
I have a few questions regarding the method.
Why do we need the gan to supervise the spatial transformer?
What happened if we take real images as input and specify one image as the target for all training pairs? 
Is that because GAN makes the training easier?
Also, how hard is it to make the whole framework work? The paper is elegant but there are lots of components in the code.

**Comment by wpeebles** [comment]
Hi @tankche1, good questions! See my responses below:

> Why do we need the gan to supervise the spatial transformer? What happened if we take real images as input and specify one image as the target for all training pairs? Is that because GAN makes the training easier?

There are two problems with using a single real image as the target for all real training pairs. 

Problem 1: It is unclear _what_ image should be the target. For example, if we were training the Spatial Transformer on real images from LSUN Cats, imagine if we happened to pick the target as a real image that only showed a cat's back (there are many of these images in the LSUN Cats dataset). This would make it impossible to ever find correspondence for a cat's face! It's really important to find a "good" target image because it dictates what correspondences the Spatial Transformer will be able to learn.

Using GAN-Supervision avoids this problem because it lets us _learn_ the target image jointly with the Spatial Transformer. This allows us to "search" the dataset of unaligned images (represented by a GAN) to find the best possible target image by backpropagating through a pre-trained GAN generator into its latent code.

Problem 2: In diverse datasets like LSUN, there is a lot of diversity in style. For example, there are orange cats, black cats and white cats in LSUN Cats. Imagine that the real image we selected as a target happened to be of a black cat. It would be impossible for the Spatial Transformer to learn to warp an image of white or orange cats to this black cat because the colors are different. 

GAN-Supervision gets around this problem too because modern GANs do a great job at disentangling style from pose. This lets us synthesize a different target image for each pair. The target retains the appearance (e.g., fur color) of the input image but is rendered in a consistent pose across all pairs. We have an ablation in Table 3 in our paper which shows using a single learned fake image as the target for all pairs works a lot worse.

> Also, how hard is it to make the whole framework work? 

In my experience, it's been pretty easy to get the unimodal models to work well on a bunch of datasets (LSUN Cats/Dogs/Bicycles, CUB, In-The-Wild CelebA, etc.). The key seems to be having a good pre-trained StyleGAN model and setting the `--ndirs` value (`N` in the paper) to a relatively small value. The other "tricks" are the total variation regularizer on the flow and the "Smoothly-congealed targets" we describe in Supplementary Material B.3 in our paper.

The clustering models (LSUN Cars and Horses) can be a bit more finicky to train and prone to instability compared to the relatively stable unimodal models.

> The paper is elegant but there are lots of components in the code.

Most of the complexity in this codebase is unfortunately related to supporting the clustering version of GANgealing that we use for LSUN Cars and Horses :( If you ignore the clustering-specific sections, the unimodal GANgealing algorithm that we use for all other datasets is mostly straightforward in the code. If you have any questions about specific parts of the repo, please feel free to ask!

**Comment by tankche1** [comment]
Thanks for your response! That addresses most of my confusion.
Another question:
Can we overfit a small dataset (e.g., 10 dog images) to make it align with another real dog image?  This helps me understand the importance of controlling the target images' pose and appearance.

**Comment by wpeebles** [comment]
To make sure I understand: are you asking if it's possible to overfit the Spatial Transformer Network to 10 pairs of real images, where the target image is a single real image of the dog? I think it's unlikely this would work without explicit supervision of the warp parameters or a perceptual loss that is nearly invariant to appearance, mainly because I would think the reconstruction loss will be very high if there is appearance differences between the 10 images and the target image. But it would be interesting to try!

**Comment by tankche1** [comment]
Thanks for the reply.

Yes, this is what I am asking.

I do try and it seems that the network can learn nothing. Possibly because of the reason you mentioned.

**Comment by wpeebles** [comment]
Yeah, this result makes sense to me. Using a perceptual reconstruction loss seems to help alleviate some differences between input and target pairs (e.g., differences in background, very small differences in fur color for LSUN Cats, etc.), but they are still quite sensitive to significantly different appearances.

**Comment by Dong09** [comment]
> 



> Hi @tankche1. It looks like your environment is either having trouble finding CUDA or building the CUDA extensions from the [rosinality StyleGAN2 repo](https://github.com/rosinality/stylegan2-pytorch).
> 
> Can you verify CUDA/cuDNN is working:
> 
> ```
> import torch
> x = torch.randn(2, 3, device='cuda')
> print(x)
> print('success')
> ```
> 
> And if that works, try this (running from the `gangealing` directory):
> 
> ```
> from gangealing.models.stylegan2.networks import Generator
> g = Generator(128, 512, 8).to('cuda')
> print('success')
> ```

hi,i try to run your second code but i get something wrong. 

my envirnoment : cuda 11.0   pytorch 1.7.1

this is my error:
![QQ截图20220527115801](https://user-images.githubusercontent.com/45942487/170626374-b11def48-aaee-457e-86ba-14d5f6e25ccc.png)

Any help would be appreciated.
