### ISSUE TITLE
the commond to train stylegan2

### ISSUE THREAD

**Issue by adaxigua** [wpeebles/gangealing#16]
In this project's code, the sylegan is likely based on `https://github.com/rosinality/stylegan2-pytorch`

But I found no args setting in `https://github.com/rosinality/stylegan2-pytorch`. 

I have try to set args refer to `https://github.com/NVlabs/stylegan2`, but the result is not good.

Could you share your  training scripts for the stylegan2?

**Comment by wpeebles** [comment]
Hi @wangherr. All of the StyleGAN models I used for the paper were either trained by me using NVIDIA's official TensorFlow implementations of [StyleGAN2](https://github.com/NVlabs/stylegan2) and [StyleGAN2-ADA](https://github.com/NVlabs/stylegan2-ada) (LSUN Bicycles/Cars/TVs, CUB, CelebA), or were models released directly by NVIDIA (LSUN Cats/Dogs/Horses). For all models, I converted them to the rosinality repo using their `convert_weight.py` script. 

I unfortunately don't have the exact training commands for the StyleGAN models on-hand, but these were my general steps for training in the official [ADA codebase](https://github.com/NVlabs/stylegan2-ada):

----

(1) For the LSUN datasets, I used the standard `dataset_tool.py create_lsun` command that center-crops images that is described in the ADA repo's "Preparing datasets" section. The only difference is that I did *not* use the `max_images` argument (i.e., I trained the StyleGAN models on all images in an LSUN category).

(2) I think this was the command I used for training most of the LSUN models:

```python
python train.py --outdir=results/ --gpus=8 --data=datasets/my_lsun_dataset --gamma=10.0 --cfg=stylegan2 --aug=noaug --kimg=100000 
```

Some things to note:

**ADA**: I disabled ADA in most of my experiments since LSUN is already very large and does not seem to benefit much from data augmentation. If your dataset is small, you may get more value out of using it. 

**Gamma**: I tried two values of `--gamma` for various LSUN datasets (0.4096 and 10), and always found 10 worked better. But in general it's hard to predict what `gamma` is best for a new dataset, so you may need to try out a few values if you're using a new dataset.

**Training Length**: The exact number of kimgs I trained for was variable for different datasets. For example, I trained the LSUN Bicycles model for close to 100,000 kimg because FID was still decreasing, although this was probably excessive IMO. In general I stopped  StyleGAN training when FID appeared to heavily saturate.

If you end up training your StyleGAN models with the ADA codebase and want to use them with GANgealing, make sure to specify `--num_fp16_res 4` when calling GANgealing's `train.py` script. If you omit this argument, the samples from your pre-trained Generator may look very strange and distorted due to some special mixed precision ops used by the StyleGAN authors.

Let me know if any additional clarification is needed!

**Comment by adaxigua** [comment]
Thanks，I will try it！
