### ISSUE TITLE
RuntimeError: Error building extension '_splat' during visualization

### ISSUE THREAD

**Issue by petercmh01** [wpeebles/gangealing#23]
Hello: Thank you so much for the awsome work and consistently helping with all the question

After I trained a model on my own dataset, I tried to run propagate_to_image.py with a mask I created my own to visualize the dense correspondence mask. but when it runs to building extension I got this error of RuntimeError: Error building extension '_splat' during visualization. 

If I run without any mask (just congealing the input images) I get no errors. 

I'm using cuda = 11.7 and pytorch = 1.11.0. 

Is this likely be a cuda installation problem? 

Thank you

**Comment by petercmh01** [comment]
I was able to solve it by change my pytorch to 1.10.1 and torchvision to 0.11.2, the issue was due to the latest pytorch (1.11.0)  delete THC/THC.h file/folder when building extension.

**Comment by xavigiro** [comment]
I addressed the issue from another perspective. The problem comes from the use of [THCudaCheck](https://github.com/wpeebles/gangealing/blob/9c311fd65a2587d4503f92c32b94b29a124227fa/utils/splat2d_cuda/src/splat_gpu.c#L7) in `splat_gpu.c` . This function is [deprecated](https://github.com/pytorch/pytorch/pull/66391) since PyTorch 1.11.

One alternative is replacing `THCudaCheck` by the macro `C10_CUDA_CHECK`, which is already [defined](https://github.com/pytorch/pytorch/blob/master/c10/cuda/CUDAException.h) in PyTorch. In particular, I just used `C10_CUDA_CHECK(cudaGetLastError())` instead of `THCudaCheck(cudaGetLastError())`.
