### ISSUE TITLE
about StyleGan2 ADA training process

### ISSUE THREAD

**Issue by Dong09** [wpeebles/gangealing#26]
hello ***wpeebles***,
i try to train the styleGan net with my own datasets,and i used a 2080Ti 12G GPU batchsize=4 to train 4 days, 
it returned this,and **I want to know if I didn't have enough training time or if I failed.**

![QQ截图20220629183619](https://user-images.githubusercontent.com/45942487/176416774-e903f0fb-c509-4bad-a608-54c85611ed99.png)

**Comment by wpeebles** [comment]
Seems like your run probably collapsed. Generated images shouldn't look like this at any stage of stylegan2-ada training after the first few minutes. Are you training with a per-gpu batch size of 4 (`minibatch_gpu`) or a global batch size of 4 (`minibatch_size`)? If it's the latter, I would try increasing `minibatch_size` to like 32 to stabilize training (your GPU won't run out of memory since they use gradient accumulation). You should also make sure that the grid of saved real images `reals.png` looks correct (if they don't, it's possible the issue could be a dataset pre-processing error).

**Comment by Dong09** [comment]
Thanks for your reply, 

I try to change my batch_size from 4 to 32,16 even 8,but it cannot work successful ,I always get error about cuda out of memory. 

I used following script:
``` python train.py --outdir=./training-runs --data=G:\\xxx --gpus=1 --batch=32 ```

**Comment by wpeebles** [comment]
I think the PyTorch versions of stylegan2-ada might automatically set the per-gpu batch size based on the `--batch` argument. You may need to manually set the `batch_size` and `batch_gpu` inputs to their `training_loop` function instead.  E.g., manually try passing `batch_size=32` and `batch_gpu=4` to that function instead of using command line args.

**Comment by Gjergj121** [comment]
Hi Dong09. I am also trying to train the GANgealing models with some other datasets. What datasets did you use, and which dataset would you suggest me to try?
